//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.03 at 09:06:09 AM IST 
//


package com.tibco.schemas._5xcode_after.mig.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IT_Staff">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IT_EmpID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IT_EmpName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IT_EmpAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NonIT_Staff">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NonIT_EmpID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NonIT_EmpName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NonIT_EmpAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Management_Staff">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Management_EmpID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Management_EmpName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Management_EmpAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Contractor_Staffs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Contractor_EmpID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Contractor_EmpName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Contractor_EmpAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itStaff",
    "nonITStaff",
    "managementStaff",
    "contractorStaffs"
})
@XmlRootElement(name = "CG_Employee_Set")
public class CGEmployeeSet {

    @XmlElement(name = "IT_Staff", required = true)
    protected CGEmployeeSet.ITStaff itStaff;
    @XmlElement(name = "NonIT_Staff", required = true)
    protected CGEmployeeSet.NonITStaff nonITStaff;
    @XmlElement(name = "Management_Staff", required = true)
    protected CGEmployeeSet.ManagementStaff managementStaff;
    @XmlElement(name = "Contractor_Staffs", required = true)
    protected CGEmployeeSet.ContractorStaffs contractorStaffs;

    /**
     * Gets the value of the itStaff property.
     * 
     * @return
     *     possible object is
     *     {@link CGEmployeeSet.ITStaff }
     *     
     */
    public CGEmployeeSet.ITStaff getITStaff() {
        return itStaff;
    }

    /**
     * Sets the value of the itStaff property.
     * 
     * @param value
     *     allowed object is
     *     {@link CGEmployeeSet.ITStaff }
     *     
     */
    public void setITStaff(CGEmployeeSet.ITStaff value) {
        this.itStaff = value;
    }

    /**
     * Gets the value of the nonITStaff property.
     * 
     * @return
     *     possible object is
     *     {@link CGEmployeeSet.NonITStaff }
     *     
     */
    public CGEmployeeSet.NonITStaff getNonITStaff() {
        return nonITStaff;
    }

    /**
     * Sets the value of the nonITStaff property.
     * 
     * @param value
     *     allowed object is
     *     {@link CGEmployeeSet.NonITStaff }
     *     
     */
    public void setNonITStaff(CGEmployeeSet.NonITStaff value) {
        this.nonITStaff = value;
    }

    /**
     * Gets the value of the managementStaff property.
     * 
     * @return
     *     possible object is
     *     {@link CGEmployeeSet.ManagementStaff }
     *     
     */
    public CGEmployeeSet.ManagementStaff getManagementStaff() {
        return managementStaff;
    }

    /**
     * Sets the value of the managementStaff property.
     * 
     * @param value
     *     allowed object is
     *     {@link CGEmployeeSet.ManagementStaff }
     *     
     */
    public void setManagementStaff(CGEmployeeSet.ManagementStaff value) {
        this.managementStaff = value;
    }

    /**
     * Gets the value of the contractorStaffs property.
     * 
     * @return
     *     possible object is
     *     {@link CGEmployeeSet.ContractorStaffs }
     *     
     */
    public CGEmployeeSet.ContractorStaffs getContractorStaffs() {
        return contractorStaffs;
    }

    /**
     * Sets the value of the contractorStaffs property.
     * 
     * @param value
     *     allowed object is
     *     {@link CGEmployeeSet.ContractorStaffs }
     *     
     */
    public void setContractorStaffs(CGEmployeeSet.ContractorStaffs value) {
        this.contractorStaffs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Contractor_EmpID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Contractor_EmpName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Contractor_EmpAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contractorEmpID",
        "contractorEmpName",
        "contractorEmpAge"
    })
    public static class ContractorStaffs {

        @XmlElement(name = "Contractor_EmpID", required = true)
        protected String contractorEmpID;
        @XmlElement(name = "Contractor_EmpName", required = true)
        protected String contractorEmpName;
        @XmlElement(name = "Contractor_EmpAge")
        protected int contractorEmpAge;

        /**
         * Gets the value of the contractorEmpID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContractorEmpID() {
            return contractorEmpID;
        }

        /**
         * Sets the value of the contractorEmpID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContractorEmpID(String value) {
            this.contractorEmpID = value;
        }

        /**
         * Gets the value of the contractorEmpName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContractorEmpName() {
            return contractorEmpName;
        }

        /**
         * Sets the value of the contractorEmpName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContractorEmpName(String value) {
            this.contractorEmpName = value;
        }

        /**
         * Gets the value of the contractorEmpAge property.
         * 
         */
        public int getContractorEmpAge() {
            return contractorEmpAge;
        }

        /**
         * Sets the value of the contractorEmpAge property.
         * 
         */
        public void setContractorEmpAge(int value) {
            this.contractorEmpAge = value;
        }

		@Override
		public String toString() {
			return "ContractorStaffs [contractorEmpID=" + contractorEmpID + ", contractorEmpName=" + contractorEmpName
					+ ", contractorEmpAge=" + contractorEmpAge + "]";
		}
        
        

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IT_EmpID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IT_EmpName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IT_EmpAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itEmpID",
        "itEmpName",
        "itEmpAge"
    })
    public static class ITStaff {

        @XmlElement(name = "IT_EmpID", required = true)
        protected String itEmpID;
        @XmlElement(name = "IT_EmpName", required = true)
        protected String itEmpName;
        @XmlElement(name = "IT_EmpAge")
        protected int itEmpAge;

        /**
         * Gets the value of the itEmpID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getITEmpID() {
            return itEmpID;
        }

        /**
         * Sets the value of the itEmpID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setITEmpID(String value) {
            this.itEmpID = value;
        }

        /**
         * Gets the value of the itEmpName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getITEmpName() {
            return itEmpName;
        }

        /**
         * Sets the value of the itEmpName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setITEmpName(String value) {
            this.itEmpName = value;
        }

        /**
         * Gets the value of the itEmpAge property.
         * 
         */
        public int getITEmpAge() {
            return itEmpAge;
        }

        /**
         * Sets the value of the itEmpAge property.
         * 
         */
        public void setITEmpAge(int value) {
            this.itEmpAge = value;
        }

		@Override
		public String toString() {
			return "ITStaff [itEmpID=" + itEmpID + ", itEmpName=" + itEmpName + ", itEmpAge=" + itEmpAge + "]";
		}
        
        

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Management_EmpID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Management_EmpName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Management_EmpAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "managementEmpID",
        "managementEmpName",
        "managementEmpAge"
    })
    public static class ManagementStaff {

        @XmlElement(name = "Management_EmpID", required = true)
        protected String managementEmpID;
        @XmlElement(name = "Management_EmpName", required = true)
        protected String managementEmpName;
        @XmlElement(name = "Management_EmpAge")
        protected int managementEmpAge;

        /**
         * Gets the value of the managementEmpID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getManagementEmpID() {
            return managementEmpID;
        }

        /**
         * Sets the value of the managementEmpID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setManagementEmpID(String value) {
            this.managementEmpID = value;
        }

        /**
         * Gets the value of the managementEmpName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getManagementEmpName() {
            return managementEmpName;
        }

        /**
         * Sets the value of the managementEmpName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setManagementEmpName(String value) {
            this.managementEmpName = value;
        }

        /**
         * Gets the value of the managementEmpAge property.
         * 
         */
        public int getManagementEmpAge() {
            return managementEmpAge;
        }

        /**
         * Sets the value of the managementEmpAge property.
         * 
         */
        public void setManagementEmpAge(int value) {
            this.managementEmpAge = value;
        }

		@Override
		public String toString() {
			return "ManagementStaff [managementEmpID=" + managementEmpID + ", managementEmpName=" + managementEmpName
					+ ", managementEmpAge=" + managementEmpAge + "]";
		}
        
        
        

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NonIT_EmpID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NonIT_EmpName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NonIT_EmpAge" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nonITEmpID",
        "nonITEmpName",
        "nonITEmpAge"
    })
    public static class NonITStaff {

        @XmlElement(name = "NonIT_EmpID", required = true)
        protected String nonITEmpID;
        @XmlElement(name = "NonIT_EmpName", required = true)
        protected String nonITEmpName;
        @XmlElement(name = "NonIT_EmpAge")
        protected int nonITEmpAge;

        /**
         * Gets the value of the nonITEmpID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNonITEmpID() {
            return nonITEmpID;
        }

        /**
         * Sets the value of the nonITEmpID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNonITEmpID(String value) {
            this.nonITEmpID = value;
        }

        /**
         * Gets the value of the nonITEmpName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNonITEmpName() {
            return nonITEmpName;
        }

        /**
         * Sets the value of the nonITEmpName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNonITEmpName(String value) {
            this.nonITEmpName = value;
        }

        /**
         * Gets the value of the nonITEmpAge property.
         * 
         */
        public int getNonITEmpAge() {
            return nonITEmpAge;
        }

        /**
         * Sets the value of the nonITEmpAge property.
         * 
         */
        public void setNonITEmpAge(int value) {
            this.nonITEmpAge = value;
        }

		@Override
		public String toString() {
			return "NonITStaff [nonITEmpID=" + nonITEmpID + ", nonITEmpName=" + nonITEmpName + ", nonITEmpAge="
					+ nonITEmpAge + "]";
		}
        
        

    }

}
