//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.03 at 09:06:09 AM IST 
//


package com.tibco.schemas._5xcode_after.mig.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.schemas._5xcode_after.mig.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.schemas._5xcode_after.mig.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CGEmployeeSet }
     * 
     */
    public CGEmployeeSet createCGEmployeeSet() {
        return new CGEmployeeSet();
    }

    /**
     * Create an instance of {@link CGEmployeeSet.ITStaff }
     * 
     */
    public CGEmployeeSet.ITStaff createCGEmployeeSetITStaff() {
        return new CGEmployeeSet.ITStaff();
    }

    /**
     * Create an instance of {@link CGEmployeeSet.NonITStaff }
     * 
     */
    public CGEmployeeSet.NonITStaff createCGEmployeeSetNonITStaff() {
        return new CGEmployeeSet.NonITStaff();
    }

    /**
     * Create an instance of {@link CGEmployeeSet.ManagementStaff }
     * 
     */
    public CGEmployeeSet.ManagementStaff createCGEmployeeSetManagementStaff() {
        return new CGEmployeeSet.ManagementStaff();
    }

    /**
     * Create an instance of {@link CGEmployeeSet.ContractorStaffs }
     * 
     */
    public CGEmployeeSet.ContractorStaffs createCGEmployeeSetContractorStaffs() {
        return new CGEmployeeSet.ContractorStaffs();
    }

}
